version: "3.8"

services: 
  # Rest api
  api:
    container_name: api-ts
    build: .
    ports: 
      - "4000:4000"
    links: 
      - database
    environment:
      - MONGO_DATABASE=mern-db
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=database
    depends_on: 
      - database
    volumes: 
      - .:/app
  # Mongodb database
  database: 
    container_name: mern-db
    image: mongo
    ports:
      - "27018:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    logging: 
      driver: none